### ISSUE TITLE
Using with home bridge docker

### ISSUE THREAD

**Issue by jausto** [MnrGreg/homebridge-ecovacs-deebot#2]
Couple of questions:

1. What is the device ID? I have the DEEBOT N79S.
2. Do I put all the assets in the same area? (/usr/local/etc/)
3. Trying to set this up with my docker environment, but I don't have access /usr/local/etc/, I used cmd2 point it to a different area. but Im getting a permission denied error.

Any help would be great.

**Comment by MnrGreg** [comment]
1. Determine your devices unique DeviceID using the Sucks script while authenticating with your ECOVACS account: https://github.com/wpietri/sucks#usage

2. Binary can be anywhere but deebot.json config file is hardcoded to /usr/local/etc. You can edit the path in deebot.go and recompile as needed. Sounds like you're running on RPI so I've added the go build command for that. Rename the binary to just deebot on the RPI.

3. Have you tried mounting the deebot.json into the docker image with '-v'

**Comment by jlhunter2008** [comment]
@jausto did you ever get this working? If so what were the steps?

**Comment by jausto** [comment]
I gave up 

Jaime

**Comment by jlhunter2008** [comment]
@jausto did you find another solution?

**Comment by jausto** [comment]
I didn’t, I just gave it away. :(

**Comment by MnrGreg** [comment]
The N79S model should work fine. This is the model I have.
