### ISSUE TITLE
Using on Mac Mini

### ISSUE THREAD

**Issue by jlhunter2008** [MnrGreg/homebridge-ecovacs-deebot#3]
I have updated the deebot.json file with my personal information and added it to the /usr/local/etc folder; however, when I turn on the Vacuum I get a "No Response" message in the Home App of Homekit. Am I missing something? Where are the other files suppose to go? Any help would be greatly appreciated.

**Comment by MnrGreg** [comment]
Either 'go build' the deebot binary on your Mac or rename the existing `deebot-darwin` binary to `deebot`. Make sure its chmod executable and place it in a common path such as /usr/local/bin. Validate that it's working by running 'deebot status'.
